name: Deploy Actions App

on: 
  push:
    branches:
      - main
    tags:
      - [0-9]+.[0-9]+.[0-9]+*
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploying
        run: echo "Deploying App"
      - name: Testing App
        run: echo "Testing App"

